services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/peeper
      - bundle:/usr/local/bundle
    command: ./bin/rails-entrypoint.sh
  client:
    build:
      context: .
      dockerfile: Dockerfile.ts
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/client
volumes:
  bundle:
